#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root! Use sudo command."
  exit 1
fi

cd "$(dirname "$0")"

echo -n "" > ./logs/on-change-stdout.txt
echo -n "" > ./logs/on-change-stderr.txt
