#!/usr/bin/env bash
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root! Use sudo command."
  exit 1
fi

sudo launchctl remove hosts-cop
sudo rm -rf /Library/LaunchDaemons/hosts-cop.plist

echo "Hosts cop have been stopped!"
echo "Run 'sudo ./start' to restart."
