#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser(description='Check if /etc/hosts has less entries now.')
parser.add_argument('--previous', required=True, help='path to the previous version of /etc/hosts')
parser.add_argument('--silent', action='store_true', help='path to the previous version of /etc/hosts')
args = parser.parse_args()

def count_blocked(hosts_content):
  lines = hosts_content.splitlines()
  actual = [line for line in lines if line and not line.startswith('#')]
  return len(actual)

previous_etc_hosts_content = open(args.previous, "r").read()
current_etc_hosts_content = open("/etc/hosts", "r").read()

previous_count = count_blocked(previous_etc_hosts_content)
current_count = count_blocked(current_etc_hosts_content)

if not args.silent:
  print("Previous", previous_count)
  print("Current", current_count)

if current_count < previous_count:
  if not args.silent:
    print("Current /etc/hosts contains less entries!")
  sys.exit(1)

