#!/usr/bin/env bash
cd "$(dirname "$0")"

broadcast_message() {
	printf "$1" | wall
}

console_user() {
	python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");'
}

display_notification() { # $1: message $2: title
	message=${1:-"Message"}
	title=${2:-"Script Notification"}
	user=$(console_user)
    if [[ $user != "" ]]; then
        uid=$(id -u "$user")
		launchctl asuser $uid /usr/bin/osascript <<-EndOfScript
			display notification "$message" with title "$title"
		EndOfScript
	fi
}

if test -f ../user/lock; then
	exit 0
fi

if `./compare-hosts --silent --previous=../user/previous-hosts.txt`; then
	echo "OK"
else
	should_write_back=true
  MESSAGE="I'm putting /etc/hosts back...\n"

	# broadcast_message "$MESSAGE"
	display_notification "$MESSAGE" "Hosts cop 👮‍♀️"

	if [ "$should_write_back" = true ] ; then
		touch ../user/lock
		cat ../user/previous-hosts.txt > /etc/hosts
		rm ../user/lock
	fi
fi

cat /etc/hosts > ../user/previous-hosts.txt
